### ISSUE TITLE
transaction.run hangs, callback is not called

### ISSUE THREAD

**Issue by andresmatasuarez** [anand-seeenivasagam/mongoose-transaction#3]
Hi there!

I came across what I think is a bug in the module. Due to some migration process I needed to implement, I ended up using this module, as I need to ensure that all Mongo operations execute successfully, or none at all.

I created a transaction, called the `update` method a few times, and when I invoked the `run` method to execute all the commands, it just hanged, never returning.

I debugged the code and found this excerpt (`index.js`, line 63):

``` javascript
                if(errs.length !== 0){
                    var rollbacksDeffered = [];
                    if (successDocData.length !== 0){
                        successDocData.forEach(function(docData){
                            rollbacksDeffered.push(rollback(docData));
                        });

                        $.when.apply($, rollbacksDeffered).done(function(docs){
                            callback(docs);
                        });
                    }
                } else {
                    callback(null, docs);
                }
```

The `update` calls I were making were causing validation errors in all the Mongo documents involved, so the first condition `errs.length !== 0` was true, but the second one `successDocData.length !== 0` was false, as every command had some validation error. As you can see, if that two conditions are met, `callback` is not executed at all, so method never resolves. Consequently, my API just hanged waiting for it to complete.

I made a PR adding and `else` clause to the `successDocData.length !== 0` condition and calling `callback(errs, null)`

In addition, I think that in case there is at least one error and one or more documents to be rollback-ed, the method should call `callback(errs, docs)` instead of `callback(docs)`. But this is just an idea, not included in the PR.

**Comment by anand-io** [comment]
Issue is solve with #4
